name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential libssl-dev libffi-dev libsqlite3-dev libbz2-dev
          sudo apt-get install -y openjdk-17-jdk unzip wget

      - name: Install Android SDK Command Line Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/Android/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/Android/cmdline-tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          mv $HOME/Android/cmdline-tools/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME --install "build-tools;33.0.0" "platform-tools" "platforms;android-33" "ndk;25.1.8937393"

      - name: Verify SDK installation
        run: sdkmanager --list

      - name: Build APK
        env:
          ANDROID_HOME: $HOME/Android/Sdk
          ANDROID_NDK_HOME: $HOME/Android/Sdk/ndk/25.1.8937393
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: ./bin/*.apk
